packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.1.1
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^8.1.0
  '@iconify-json/carbon': ^1.2.6
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/core': ^2.3.1
  '@shikijs/engine-javascript': ^2.3.1
  '@shikijs/engine-oniguruma': ^2.3.1
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/node': ^22.13.1
  '@types/semver': ^7.5.8
  '@unocss/eslint-config': ^65.4.3
  '@unocss/eslint-plugin': ^65.4.3
  '@unocss/reset': ^65.4.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/expect': ^3.0.5
  '@vue-macros/volar': ^0.30.14
  '@vueuse/core': ^12.5.0
  adm-zip: ^0.5.16
  bumpp: ^10.0.2
  chai: ^5.1.2
  chalk: ^5.4.1
  cson: ^8.4.0
  dotenv: ^16.4.7
  eslint: ^9.19.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.2.1
  jsonc-parser: ^3.3.1
  lint-staged: ^15.4.3
  octokit: ^4.1.0
  ofetch: ^1.4.1
  ohash: ^1.1.4
  p-limit: ^6.2.0
  pnpm: ^9.15.5
  rimraf: ^6.0.1
  semver: ^7.7.1
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.4.3
  unplugin-auto-import: ^19.0.0
  unplugin-vue-components: ^28.0.0
  unplugin-vue-macros: ^2.14.2
  unplugin-vue-router: ^0.11.2
  vite: ^6.1.0
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  yaml: ^2.7.0
