packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.9.2
  '@antfu/ni': ^0.23.1
  '@antfu/utils': ^0.7.10
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/svg-spinners': ^1.2.1
  '@shikijs/core': ^1.23.1
  '@types/adm-zip': ^0.5.6
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/json-stable-stringify': ^1.1.0
  '@types/node': ^22.9.3
  '@types/semver': ^7.5.8
  '@unocss/eslint-config': ^0.64.1
  '@unocss/eslint-plugin': ^0.64.1
  '@unocss/reset': ^0.64.1
  '@vitejs/plugin-vue': ^5.2.0
  '@vitest/expect': ^2.1.5
  '@vue-macros/volar': ^0.30.6
  '@vueuse/core': ^11.3.0
  adm-zip: ^0.5.16
  bumpp: ^9.8.1
  chai: ^5.1.2
  chalk: ^5.3.0
  cson: ^8.4.0
  dotenv: ^16.4.5
  eslint: ^9.15.0
  esno: ^4.8.0
  fast-glob: ^3.3.2
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.1.1
  jsonc-parser: ^3.3.1
  lint-staged: ^15.2.10
  octokit: ^4.0.2
  ofetch: ^1.4.1
  oniguruma-to-js: ^0.4.3
  p-limit: ^6.1.0
  pnpm: ^9.14.2
  rimraf: ^6.0.1
  semver: ^7.6.3
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  typescript: ^5.7.2
  unbuild: ^2.0.0
  unocss: ^0.64.1
  unplugin-auto-import: ^0.18.5
  unplugin-vue-components: ^0.27.4
  unplugin-vue-macros: ^2.13.4
  unplugin-vue-router: ^0.10.8
  vite: ^5.4.11
  vitest: ^2.1.5
  vue: ^3.5.13
  vue-router: ^4.4.5
  vue-tsc: ^2.1.10
  yaml: ^2.6.1
