packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.16.2
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@iconify-json/carbon': ^1.2.10
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/core': ^3.7.0
  '@shikijs/engine-javascript': ^3.7.0
  '@shikijs/engine-oniguruma': ^3.7.0
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/node': ^24.0.13
  '@types/semver': ^7.7.0
  '@unocss/eslint-config': ^66.3.3
  '@unocss/eslint-plugin': ^66.3.3
  '@unocss/reset': ^66.3.3
  '@vitejs/plugin-vue': ^6.0.0
  '@vitest/expect': ^3.2.4
  '@vue-macros/volar': ^3.0.0-beta.15
  '@vueuse/core': ^13.5.0
  adm-zip: ^0.5.16
  bumpp: ^10.2.0
  chai: ^5.2.1
  chalk: ^5.4.1
  cson: ^8.4.0
  dotenv: ^17.2.0
  eslint: ^9.31.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.3.0
  jsonc-parser: ^3.3.1
  lint-staged: ^16.1.2
  octokit: ^5.0.3
  ofetch: ^1.4.1
  ohash: ^2.0.11
  oniguruma-parser: ^0.12.1
  oniguruma-to-es: ^4.3.3
  p-limit: ^6.2.0
  pnpm: ^10.13.1
  rimraf: ^6.0.1
  semver: ^7.7.2
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.3
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.8.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.14.0
  vite: ^7.0.4
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-router: ^4.5.1
  vue-tsc: ^3.0.1
  yaml: ^2.8.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
