packages:
  - playground
  - packages/*
  - examples/*

catalog:
  '@antfu/eslint-config': ^5.2.0
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@iconify-json/carbon': ^1.2.11
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/core': ^3.9.2
  '@shikijs/engine-javascript': ^3.9.2
  '@shikijs/engine-oniguruma': ^3.9.2
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/node': ^24.2.0
  '@types/semver': ^7.7.0
  '@unocss/eslint-config': ^66.4.1
  '@unocss/eslint-plugin': ^66.4.1
  '@unocss/reset': ^66.4.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/expect': ^3.2.4
  '@vue-macros/volar': ^3.0.0-beta.21
  '@vueuse/core': ^13.6.0
  adm-zip: ^0.5.16
  bumpp: ^10.2.2
  chai: ^5.2.1
  chalk: ^5.5.0
  cson: ^8.4.0
  dotenv: ^17.2.1
  eslint: ^9.32.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fast-plist: ^0.1.3
  floating-vue: ^5.2.2
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.3.0
  jsonc-parser: ^3.3.1
  lint-staged: ^16.1.4
  octokit: ^5.0.3
  ofetch: ^1.4.1
  ohash: ^2.0.11
  oniguruma-parser: ^0.12.1
  oniguruma-to-es: ^4.3.3
  p-limit: ^6.2.0
  pnpm: ^10.14.0
  rimraf: ^6.0.1
  semver: ^7.7.2
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.2
  unbuild: ^3.6.0
  unocss: ^66.4.1
  unplugin-auto-import: ^20.0.0
  unplugin-vue-components: ^29.0.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.15.0
  vite: ^7.1.1
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-router: ^4.5.1
  vue-tsc: ^3.0.5
  yaml: ^2.8.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
