packages:
  - playground
  - packages/*
  - examples/*

catalog:
  '@antfu/eslint-config': ^6.0.0
  '@antfu/ni': ^27.0.0
  '@antfu/utils': ^9.3.0
  '@iconify-json/carbon': ^1.2.14
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/core': ^3.13.0
  '@shikijs/engine-javascript': ^3.13.0
  '@shikijs/engine-oniguruma': ^3.13.0
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/node': ^24.9.1
  '@types/semver': ^7.7.1
  '@unocss/eslint-config': ^66.5.4
  '@unocss/eslint-plugin': ^66.5.4
  '@unocss/reset': ^66.5.4
  '@vitejs/plugin-vue': ^6.0.1
  '@vue-macros/volar': ^3.1.1
  '@vueuse/core': ^14.0.0
  adm-zip: ^0.5.16
  bumpp: ^10.3.1
  chalk: ^5.6.2
  cson: ^8.4.0
  dotenv: ^17.2.3
  eslint: ^9.38.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fast-plist: ^0.1.3
  floating-vue: ^5.2.2
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.3.0
  jsonc-parser: ^3.3.1
  lint-staged: ^16.2.6
  octokit: ^5.0.4
  ofetch: ^1.4.1
  ohash: ^2.0.11
  oniguruma-parser: ^0.12.1
  oniguruma-to-es: ^4.3.3
  p-limit: ^7.2.0
  pnpm: ^10.19.0
  rimraf: ^6.0.1
  semver: ^7.7.3
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.5.4
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.16.0
  vite: ^7.1.12
  vitest: ^4.0.2
  vue: ^3.5.22
  vue-router: ^4.6.3
  vue-tsc: ^3.1.1
  yaml: ^2.8.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
