packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.8.1
  '@antfu/ni': ^24.1.0
  '@antfu/utils': ^9.1.0
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/core': ^3.2.0
  '@shikijs/engine-javascript': ^3.2.0
  '@shikijs/engine-oniguruma': ^3.2.0
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/node': ^22.13.10
  '@types/semver': ^7.5.8
  '@unocss/eslint-config': ^66.0.0
  '@unocss/eslint-plugin': ^66.0.0
  '@unocss/reset': ^66.0.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/expect': ^3.0.8
  '@vue-macros/volar': ^3.0.0-beta.4
  '@vueuse/core': ^13.0.0
  adm-zip: ^0.5.16
  bumpp: ^10.0.3
  chai: ^5.2.0
  chalk: ^5.4.1
  cson: ^8.4.0
  dotenv: ^16.4.7
  eslint: ^9.22.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.2.1
  jsonc-parser: ^3.3.1
  lint-staged: ^15.4.3
  octokit: ^4.1.2
  ofetch: ^1.4.1
  ohash: ^2.0.11
  oniguruma-parser: ^0.7.0
  oniguruma-to-es: ^4.1.0
  p-limit: ^6.2.0
  pnpm: ^10.6.2
  rimraf: ^6.0.1
  semver: ^7.7.1
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.0.0
  unplugin-auto-import: ^19.1.1
  unplugin-vue-components: ^28.4.1
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.12.0
  vite: ^6.2.1
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  yaml: ^2.7.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
